version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: antiques-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - antiques-network
    profiles:
      - dev-tools
